[package]
name = "cargo_io"
version = "0.1.0"
edition = "2021"
authors = ["volh lehongvi19x@gmail.com"]
description = "A simple Rust library."
repository = "https://github.com/lehongvo/RUST_BLOCKCHAIN_TUTORIAL/blob/main/cargo_io/src/lib.rs"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.dev]
opt-level = 1
debug = true

[profile.release]
opt-level = 3
debug = false

[lib]
name = "my_library"